version: "3.8"

services:

    api:
        container_name: api-container
        build: ./flask_api
        restart: always
        
        command: uwsgi --ini app.ini

        environment:
            - CHANNEL_ACCESS_TOKEN=${CHANNEL_ACCESS_TOKEN}
            - CHANNEL_SECRET=${CHANNEL_SECRET}
        volumes: 
            - api_data:/docker_api
            #把uwsgi log 拿出來
            - ./uwsgi_log:/uwsgi_log
            - ./flask_api/app:/docker_api/app

    nginx:
        container_name: nginx-container
        build: ./nginx
        restart: always

        ports: 
            - "443:443"
              
        volumes: 
            - api_data:/docker_api
            #把nginx log 拿出來  
            - ./nginx_log:/var/log/nginx
            - ./nginx/cert:/etc/nginx/cert
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/flask_app.conf:/etc/nginx/sites-available/flask_app.conf
        depends_on: 
            - api

volumes:
    api_data: 
